server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Source, Gateway
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**, /api/users/**, /api/auth/**
          filters:
            - StripPrefix=1
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**, /api/rooms/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
